#!/usr/bin/env bash
# test-attribution-guard.sh — regression tests for the AI-attribution guard.
# Pipes each sample commit message (via a temp file, exactly as git does) through
# .githooks/commit-msg, which sources the same .githooks/ai-patterns the CI guard uses.
# BLOCK = the hook must exit non-zero; PASS = it must exit 0 (human-authored controls).
#   bash dev/test-attribution-guard.sh
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$ROOT/.githooks/commit-msg"
T="$(mktemp -d "${TMPDIR:-/tmp}/attrib-test.XXXXXX")"; trap 'rm -rf "$T"' EXIT
pass=0; fail=0; n=0

t() { # <BLOCK|PASS> <label> <message, printf %b escapes allowed>
  n=$((n+1)); local f="$T/msg$n"; printf '%b' "$3" > "$f"
  bash "$HOOK" "$f" >/dev/null 2>&1; local rc=$?
  local got=PASS; [ "$rc" -ne 0 ] && got=BLOCK
  if [ "$got" = "$1" ]; then pass=$((pass+1)); else fail=$((fail+1)); echo "  ✖ #$n [$2] want $1, got $got"; fi
}

# --- must BLOCK: the standard forms -------------------------------------------------
t BLOCK "co-author Claude"          'feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n'
t BLOCK "co-author Claude Opus"     'feat: x\n\nCo-Authored-By: Claude Opus 4 <noreply@anthropic.com>\n'
t BLOCK "co-author Codex"           'fix: x\n\nCo-authored-by: Codex <codex@openai.com>\n'
t BLOCK "co-author Copilot"         'fix: x\n\nCo-authored-by: Copilot <copilot@github.com>\n'
t BLOCK "co-author Gemini"          'fix: x\n\nCo-authored-by: Gemini <g@google.com>\n'
t BLOCK "co-author ChatGPT"         'fix: x\n\nCo-authored-by: ChatGPT <x@openai.com>\n'
t BLOCK "co-author GPT-4"           'fix: x\n\nCo-authored-by: GPT-4 <x@y.z>\n'
t BLOCK "leading space"             'fix: x\n\n  Co-Authored-By: Claude <x@y.z>\n'
t BLOCK "leading tab"               'fix: x\n\n\tCo-Authored-By: Claude <x@y.z>\n'
t BLOCK "CRLF"                      'fix: x\r\n\r\nCo-Authored-By: Claude <x@y.z>\r\n'
t BLOCK "noreply copilot bot"       'fix: x\n\nCo-authored-by: Copilot <198982749+Copilot@users.noreply.github.com>\n'
t BLOCK "claude via gh noreply"     'fix: x\n\nCo-authored-by: claude <claude@users.noreply.github.com>\n'
t BLOCK "bot@ address"              'fix: x\n\nCo-authored-by: Helper <helper-bot@example.com>\n'
t BLOCK "co-author 'AI'"            'fix: x\n\nCo-authored-by: The AI <ai@example.com>\n'
t BLOCK "generated with [Claude]"   'fix: x\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n'
t BLOCK "generated with Claude"     'fix: x\n\nGenerated with Claude Code\n'
t BLOCK "generated with AI"         'fix: x\n\nGenerated with AI assistance\n'
t BLOCK "bare robot emoji"          'fix: x\n\n🤖\n'
# --- must BLOCK: the audit's evasions (AUX-F4) --------------------------------------
t BLOCK "generated by GitHub Copilot" 'fix: x\n\nGenerated by GitHub Copilot\n'
t BLOCK "Generated-by trailer"      'fix: x\n\nGenerated-by: Claude\n'
t BLOCK "Made with Claude"          'fix: x\n\nMade with Claude\n'
t BLOCK "Assisted-by trailer"       'fix: x\n\nAssisted-by: Claude\n'
t BLOCK "Signed-off-by Claude"      'fix: x\n\nSigned-off-by: Claude <noreply@anthropic.com>\n'
t BLOCK "Reviewed-by Codex"         'fix: x\n\nReviewed-by: Codex\n'
t BLOCK "co-author Cursor"          'fix: x\n\nCo-Authored-By: Cursor <cursor@cursor.sh>\n'
t BLOCK "generated ... by ... GPT"  'fix: x\n\nThis change was generated in part by OpenAI GPT-5\n'
t BLOCK "written using Gemini"      'fix: x\n\nWritten using Gemini\n'
t BLOCK "quoted trailer"            'fix: x\n\n> Co-Authored-By: Claude <x@y.z>\n'
t BLOCK "Helped-by trailer"         'fix: x\n\nHelped-by: ChatGPT\n'
t BLOCK "mixed case key"            'fix: x\n\nco-authored-BY: CLAUDE\n'
t BLOCK "trailer in a long body"    'fix: x\n\nLots of explanation.\n\nMore.\n\nCo-authored-by: Anthropic Claude <a@b.c>\nSigned-off-by: Samuel <s@x.edu>\n'
# --- must PASS: human-authored controls ---------------------------------------------
t PASS  "plain"                     'fix: correct VanRaden denominator\n'
t PASS  "human co-author"           'feat: x\n\nCo-authored-by: Alexander Lipka <alipka@illinois.edu>\n'
t PASS  "human GitHub noreply"      'feat: x\n\nCo-authored-by: Jane Doe <12345+jdoe@users.noreply.github.com>\n'
t PASS  "human signed-off"          'feat: x\n\nSigned-off-by: Samuel Fernandes <samuelbf@uark.edu>\n'
t PASS  "human reviewed-by"         'feat: x\n\nReviewed-by: Aisha Khan <aisha@example.org>\n'
t PASS  "generated by hand prose"   'docs: tables generated by hand from the raw output\n'
t PASS  "comment lines ignored"     'fix: x\n\n# Co-Authored-By: Claude <x@y.z>\n# 🤖\n'
t PASS  "made with care prose"      'docs: figure made with ggplot2 and saved as png\n'
t PASS  "mentions selection AI-free" 'fix: rename maintain() helper; no trailers here\n'
t PASS  "word 'said' / 'aid'"       'fix: aid documentation; said helper now exported\n'
t PASS  "empty body"                '\n'

echo "attribution guard: $pass/$n cases as expected"
[ "$fail" -eq 0 ]
