# make_SNP55K_map.R
#
# Populates the `cm` column of SNP55K_maize282_maf04 with a synthetic genetic
# map and rewrites data/SNP55K_maize282_maf04.RData.
#
# The column previously existed but was a logical all-NA placeholder, so no
# recombination distances were available anywhere in the package. Meiosis
# simulation (cross/selfcross/double_haploid) needs Morgans, so this fills it in.
#
# THE MAP IS SYNTHETIC. It is generated by synthetic_map() from the AGPv2
# physical positions and is NOT derived from any published maize linkage map
# (IBM, NAM, or otherwise). Do not quote these cM values as measured
# recombination distances. See ?synthetic_map.
#
# Only `cm` changes; markers, genotypes, chromosomes and physical positions are
# untouched, so existing user code is unaffected.
#
# Usage (from package root):
#   Rscript data-raw/make_SNP55K_map.R

devtools::load_all(quiet = TRUE)

data("SNP55K_maize282_maf04", package = "simplePHENOTYPES", envir = environment())
geno <- SNP55K_maize282_maf04

stopifnot(
  identical(colnames(geno)[1:5], c("snp", "allele", "chr", "pos", "cm")),
  all(is.na(geno$cm))
)

# Nominal centromere positions as a fraction of each chromosome's marker span.
# These approximate the maize karyotype -- chromosomes 1-5 are near-metacentric
# while 6-10 have their centromeres well off centre -- but they are ROUND
# NUMBERS CHOSEN FOR THE MODEL, not measured coordinates from an assembly.
# Their only job is to put the recombination-poor region in a plausible place.
centromere_fraction <- c(
  "1" = 0.46, "2" = 0.42, "3" = 0.40, "4" = 0.46, "5" = 0.48,
  "6" = 0.31, "7" = 0.37, "8" = 0.29, "9" = 0.35, "10" = 0.36
)

chr_levels <- unique(geno$chr)
span <- tapply(geno$pos, geno$chr, function(p) c(min(p), max(p)))
centromere <- vapply(as.character(chr_levels), function(k) {
  lim <- span[[k]]
  lim[[1]] + centromere_fraction[[k]] * (lim[[2]] - lim[[1]])
}, numeric(1))

cm <- synthetic_map(
  chr        = geno$chr,
  pos        = geno$pos,
  cm_per_mb  = 0.73,
  centromere = centromere
)

original_class <- class(geno)
geno$cm <- cm
# Only `cm` may change: same class, same dimensions, same everything else.
stopifnot(identical(class(geno), original_class))
SNP55K_maize282_maf04 <- geno

# --- Report -----------------------------------------------------------------

# Reported with message()/sprintf() rather than print(): a print() override in
# the user's .Rprofile can change the signature.
mb <- vapply(as.character(chr_levels),
             function(k) diff(span[[k]]) / 1e6, numeric(1))
len <- tapply(geno$cm, geno$chr, max)[as.character(chr_levels)]
n_mk <- as.integer(table(geno$chr)[as.character(chr_levels)])

message(sprintf("%4s %7s %9s %8s %8s", "chr", "n", "Mb", "cM", "cM/Mb"))
for (k in seq_along(chr_levels)) {
  message(sprintf("%4s %7d %9.1f %8.1f %8.2f",
                  chr_levels[[k]], n_mk[[k]], mb[[k]], len[[k]],
                  len[[k]] / mb[[k]]))
}
message("\nTotal genetic length: ", round(sum(len), 0), " cM")
message("Total physical length: ", round(sum(mb), 0), " Mb")

# Monotone within chromosome, starting at 0, and ties only where markers are
# co-located: all three are required by the meiosis code.
stopifnot(
  !any(is.na(geno$cm)),
  all(tapply(geno$cm, geno$chr, function(x) !is.unsorted(x))),
  all(abs(tapply(geno$cm, geno$chr, min)) < 1e-12)
)
tied_cm <- sum(unlist(tapply(geno$cm, geno$chr, function(x) sum(duplicated(x)))))
tied_bp <- sum(unlist(tapply(geno$pos, geno$chr, function(x) sum(duplicated(x)))))
message("Tied cM positions: ", tied_cm, " (tied bp: ", tied_bp, ")")
stopifnot(tied_cm == tied_bp)

save(SNP55K_maize282_maf04,
     file = file.path("data", "SNP55K_maize282_maf04.RData"),
     compress = "xz")
message("\nWrote data/SNP55K_maize282_maf04.RData")
