# Generated by rextendr from the #[extendr] items in src/rust/src, then edited:
# the functions that return `Result` (feature `result_list`, see
# src/rust/Cargo.toml) are wrapped in `.unwrap_extendr()` (R/zzz.R), which turns
# the `list(ok, err)` the kernel returns into a value or an ordinary R error.
# Regenerating this file with rextendr::document() drops the wrapper; the
# subprocess probes in tests/testthat/test-audit-rust-crossing.R then fail.

#' Numericalize a raw 0/1/2 dosage matrix into the user-facing coding.

# nolint start

#'
#' `raw_dosage` is a flat integer vector of length `n_snp * n_samp` stored
#' **row-major** (i.e. all samples for SNP 0 come first, then all samples for
#' SNP 1, …).  Values must be 0 (hom allele-1), 1 (het), 2 (hom allele-2),
#' or `NA_integer_` (missing).
#'
#' `flip[i]` = TRUE when allele-2 is the **major** allele for SNP i (so raw 2
#' should receive the major-allele code).  FALSE means allele-1 is major.
#'
#' Returns an integer vector of the same length with values recoded per
#' `code_as` / `model` / `impute`.
#'
#' @param raw_dosage Integer vector length n_snp * n_samp, row-major.
#' @param n_snp      Number of SNPs (rows).
#' @param n_samp     Number of samples (columns).
#' @param flip       Logical vector length n_snp.
#' @param code_as    "-101" (major=1, het=0, minor=-1) or "012" (major=2, het=1, minor=0).
#' @param model      "Add", "Dom", "Left", or "Right".
#' @param impute     "None", "Middle", "Minor", or "Major".
#' @return Integer vector length n_snp * n_samp.
#' @noRd
numericalize_core <- function(raw_dosage, n_snp, n_samp, flip, code_as, model, impute) .unwrap_extendr(.Call(wrap__numericalize_core, raw_dosage, n_snp, n_samp, flip, code_as, model, impute), "numericalize_core")

#' Produce progeny genotypes from pre-drawn meiosis randomness.
#'
#' Chiasmata are concatenated and delimited by `counts`, ordered
#' `counts[event * n_chr + chr]`. Events run progeny-major: for "cross" and
#' "selfcross", event `2i` is parent 1's gamete for progeny `i` and `2i+1` is
#' parent 2's; for "dh" there is one event per progeny.
#'
#' @param loci_per_chr Integer vector of loci counts, chromosomes ascending.
#' @param positions    Map positions in Morgans, concatenated, ascending within chromosome.
#' @param p1_cis       Parent 1 cis strand as a '0'/'1' string, ascending.
#' @param p1_trans     Parent 1 trans strand.
#' @param p2_cis       Parent 2 cis strand (same as p1 for selfcross/dh).
#' @param p2_trans     Parent 2 trans strand.
#' @param chiasmata    Concatenated crossover positions.
#' @param counts       Crossovers per (event, chromosome).
#' @param flips        0/1 strand-choice per (event, chromosome).
#' @param design       "cross", "selfcross", or "dh".
#' @param n_prog       Number of progeny.
#' @return Integer vector length n_loci * n_prog, loci-major (-1/0/1).
#' @noRd
meiosis_core <- function(loci_per_chr, positions, p1_cis, p1_trans, p2_cis, p2_trans, chiasmata, counts, flips, design, n_prog) .unwrap_extendr(.Call(wrap__meiosis_core, loci_per_chr, positions, p1_cis, p1_trans, p2_cis, p2_trans, chiasmata, counts, flips, design, n_prog), "meiosis_core")

#' Progeny haplotypes from pre-drawn meiosis randomness.
#'
#' Same arguments as `meiosis_core()`, but returns the phased strands rather
#' than the `-1/0/1` genotype: element `2i` is progeny `i`'s first strand and
#' `2i + 1` its second, each a '0'/'1' string in ascending map order.
#'
#' This is what breeding programmes need. A genotype loses the phase of every
#' heterozygote, so reconstructing strands from it would make an F1 -- which is
#' heterozygous everywhere -- come out with one all-allele-1 strand and one
#' all-allele-2 strand, and every later generation would then recombine
#' haplotypes the founders never had.
#'
#' @param loci_per_chr Integer vector of loci counts, chromosomes ascending.
#' @param positions    Map positions in Morgans, concatenated.
#' @param p1_cis       Parent 1 first strand as a '0'/'1' string, ascending.
#' @param p1_trans     Parent 1 second strand.
#' @param p2_cis       Parent 2 first strand (same as p1 for selfcross/dh).
#' @param p2_trans     Parent 2 second strand.
#' @param chiasmata    Concatenated crossover positions.
#' @param counts       Crossovers per (event, chromosome).
#' @param flips        0/1 strand-choice per (event, chromosome).
#' @param design       "cross", "selfcross", or "dh".
#' @param n_prog       Number of progeny.
#' @return Character vector of length 2 * n_prog.
#' @noRd
mate_haplotypes_core <- function(loci_per_chr, positions, p1_cis, p1_trans, p2_cis, p2_trans, chiasmata, counts, flips, design, n_prog) .unwrap_extendr(.Call(wrap__mate_haplotypes_core, loci_per_chr, positions, p1_cis, p1_trans, p2_cis, p2_trans, chiasmata, counts, flips, design, n_prog), "mate_haplotypes_core")

#' Progeny of a whole batch of matings in one call, integer in and out.
#'
#' The vectorised, string-free form of `mate_haplotypes_core()` (SPEC-0020 item 2):
#' `strands` is an integer 0/1 vector of `n_strands` parental strands of
#' `length(positions)` loci each (strand after strand), in the caller's marker
#' order; `order` (1-based) maps ascending map rank to the caller's index, so
#' the progeny come back in the caller's order. `mating` holds, per mating, the
#' 1-based strand indices `p1_cis, p1_trans, p2_cis, p2_trans` (4 consecutive
#' entries); `design` and `n_prog` have one entry per mating. The meiosis events
#' are shared and consumed in mating order (`n_prog * (1 for "dh", else 2)` per
#' mating, progeny-major), so the result equals running the matings one by one
#' with their draws concatenated. The kernel draws nothing (DECISION-012).
#'
#' @param loci_per_chr Integer vector of loci counts, chromosomes ascending.
#' @param positions    Map positions in Morgans, ascending map order, concatenated.
#' @param order        1-based permutation: caller index of the locus with each map rank.
#' @param strands      Integer 0/1 vector, `n_strands` strands of n_loci entries.
#' @param n_strands    Number of parental strands in `strands`.
#' @param mating       4 * n_matings 1-based strand indices (p1_cis, p1_trans, p2_cis, p2_trans).
#' @param design       Character vector, one of "cross", "selfcross", "dh" per mating.
#' @param n_prog       Progeny per mating.
#' @param chiasmata    Concatenated crossover positions, each within [0, L] of its chromosome.
#' @param counts       Crossovers per (event, chromosome).
#' @param flips        0/1 strand-choice per (event, chromosome).
#' @return `list(cis, trans)`: integer vectors of n_loci * sum(n_prog) 0/1 entries, one progeny per column.
#' @noRd
mate_many_core <- function(loci_per_chr, positions, order, strands, n_strands, mating, design, n_prog, chiasmata, counts, flips) .unwrap_extendr(.Call(wrap__mate_many_core, loci_per_chr, positions, order, strands, n_strands, mating, design, n_prog, chiasmata, counts, flips), "mate_many_core")

#' Raw ancestry masks, one '0'/'1' string per meiosis event.
#'
#' Parity hook mirroring isqg's `spc$gamete()`. Unlike the -1/0/1 genotype —
#' a lossy 3-valued projection that cannot distinguish a cis/trans swap — the
#' mask pins the recombination algorithm on its own.
#'
#' @param loci_per_chr Integer vector of loci counts, chromosomes ascending.
#' @param positions    Map positions in Morgans, concatenated.
#' @param chiasmata    Concatenated crossover positions.
#' @param counts       Crossovers per (event, chromosome).
#' @param flips        0/1 strand-choice per (event, chromosome).
#' @return Character vector, one mask per event, ascending map order.
#' @noRd
gamete_masks_core <- function(loci_per_chr, positions, chiasmata, counts, flips) .unwrap_extendr(.Call(wrap__gamete_masks_core, loci_per_chr, positions, chiasmata, counts, flips), "gamete_masks_core")

#' Hex FNV-1a-128 of each input string (pedigree keys, DECISION-024).
#' @param x Character vector.
#' @return Character vector of 32-digit lower-case hex hashes.
#' @noRd
stable_hash_core <- function(x) .Call(wrap__stable_hash_core, x)

#' Coalescent haplotypes of one chromosome (SMC', DECISION-048).
#'
#' Returns list(pos, hap, n_total, tmrca, length): `pos` in [0, 1); `hap` an
#' integer vector of length n_sites * n_hap, sites x haplotypes column-major
#' (1 = derived allele); `n_total` the number of segregating sites before
#' subsetting; `tmrca` and `length` of the tree at position 0, `tmrca_end` of
#' the tree at position 1.
#' @noRd
coalescent_chromosome_core <- function(n_hap, theta, rho, history_times, history_sizes, seg_sites, seed) .unwrap_extendr(.Call(wrap__coalescent_chromosome_core, n_hap, theta, rho, history_times, history_sizes, seg_sites, seed), "coalescent_chromosome_core")



# nolint end
